[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = {
  LOG_LEVEL = "INFO",
  RAILWAY_ENVIRONMENT = "production",
  REQUIRE_AUTH = "true",
  PYTHONUNBUFFERED = "1"
}
